### ISSUE TITLE
add slider on the fly?

### ISSUE THREAD

**Issue by mainpart** [vanderlee/limitslider#2]
Hello. Any way to add slider on the fly via methods?

**Comment by pavlo-p** [comment]
The same question. Is there any possibility to add this functionality or maybe you can give me some guidelines and I'll add it by myself?

Thanks a lot.

**Comment by vanderlee** [comment]
Sorry for the delay. I have a rather large number of plug-ins and my backlog of issues keeps growing. I'll come around to this issue eventually, but if you could add it yourself... well... that's why it's open source ;)

You might be able to add sliders simply by calling `$element.limitslider('option', 'ranges', [...])`, with a new set of ranges including the new one. Otherwise, a new method `insert` or `add` could do the trick, depending on where you want the new slider to appear relative to the sliders you already have. Internally it's probably just a matter of splicing in the new slider in the `ranges` and probably `limits` options and calling `_change()`. And also adding suitable testcases.

**Comment by pavlo-p** [comment]
Thank you. I'll create pull request when it will be done.

**Comment by vanderlee** [comment]
Finally got round to adding an `insert` method (and added a `remove` method as well).
Was quite a nasty bit of hacking, but it seems to be working fine. Works with the old jQuery 1.3 and jQueryUI 1.8 and the current versions. I'm assuming it'll work for intermediate version as well.
